export const vehiclesStepperInitialState = [
  {
    id: 1,
    group: "vehiculos",
    step: "Información general del vehículo",
    completed: false,
    disabled: false,
    selected: true,
    link: "/vehiculos/crearVehiculo",
  },
  {
    id: 2,
    group: "vehiculos",
    step: "Tecnomecánica",
    completed: false,
    disabled: false,
    selected: false,
    link: "/vehiculos/tecnomecanica",
  },
  {
    id: 3,
    group: "vehiculos",
    step: "pólizas",
    completed: false,
    disabled: false,
    selected: false,
    link: "/vehiculos/polizas",
  },
  {
    id: 4,
    group: "vehiculos",
    step: "equipo de comunicaciones",
    completed: false,
    disabled: false,
    selected: false,
    link: "/vehiculos/equipo-de-comunicaciones",
  },
  {
    id: 5,
    group: "vehiculos",
    step: "anexos del vehículo",
    completed: false,
    disabled: false,
    selected: false,
    link: "/vehiculos/anexos-del-vehiculo",
  },
];
